# Generated by Django 5.1.4 on 2025-05-07 04:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lecturer_app", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="lecturer",
            name="user",
        ),
        migrations.AddField(
            model_name="lecturer",
            name="name",
            field=models.CharField(default="Dr. Okebanama", max_length=255),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name="Comment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "classroom",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="lecturer_app.classroom",
                    ),
                ),
                (
                    "lecturer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="lecturer_app.lecturer",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="lecturer_app.student",
                    ),
                ),
            ],
        ),
    ]
