# Generated by Django 5.1.4 on 2025-05-07 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lecturer_app", "0003_course_code"),
    ]

    operations = [
        migrations.AddField(
            model_name="comment",
            name="sentiment",
            field=models.CharField(
                choices=[("positive", "Positive"), ("negative", "Negative")],
                default="unknown",
                max_length=10,
            ),
            preserve_default=False,
        ),
    ]
